# Generated by Django 5.2 on 2025-04-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('socket', models.CharField(max_length=25)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('frequency', models.FloatField(help_text='GHz')),
            ],
            bases=('components.product',),
        ),
    ]
