# Generated by Django 5.2 on 2025-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Очікує', 'Очікує'), ('Опрацьовується', 'Опрацьовується'), ('Відправлено', 'Відправлено'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='Очікує', max_length=20, verbose_name='Order status'),
        ),
    ]
