# Generated by Django 5.2 on 2025-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=25)),
                ('socket', models.CharField(max_length=25)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('frequency', models.FloatField(help_text='GHz')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
