# Generated by Django 5.2 on 2025-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='TDP',
            field=models.IntegerField(default=0, help_text='Watt'),
        ),
    ]
