# Generated by Django 5.2 on 2025-04-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_cpu_tdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('socket', models.CharField(max_length=25)),
                ('chipset', models.CharField(max_length=25)),
                ('form_factor', models.CharField(default='ATX', max_length=25)),
                ('RAM_slots', models.IntegerField()),
                ('RAM_type', models.CharField(max_length=25)),
                ('M2_slots', models.IntegerField()),
                ('WiFi', models.BooleanField(default=False)),
                ('Bluetooth', models.BooleanField(default=False)),
                ('TDP', models.IntegerField(default=0, help_text='Watt')),
            ],
            bases=('components.product',),
        ),
    ]
