# Generated by Django 5.2 on 2025-04-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_motherboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='TDP',
        ),
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
