# Generated by Django 5.2 on 2025-04-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_remove_motherboard_tdp_product_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
    ]
