# Generated by Django 5.2 on 2025-04-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_product_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('gp_brand', models.CharField(max_length=25)),
                ('series', models.CharField(max_length=25)),
                ('memory', models.IntegerField(help_text='GB')),
                ('memory_type', models.CharField(max_length=25)),
                ('TDP', models.IntegerField(default=0, help_text='Watt')),
            ],
            bases=('components.product',),
        ),
    ]
