# Generated by Django 5.2 on 2025-04-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('capacity', models.IntegerField(help_text='GB')),
                ('RAM_type', models.CharField(max_length=25)),
                ('frequency', models.IntegerField(help_text='MHz')),
                ('number_of_modules', models.IntegerField(default=1)),
            ],
            bases=('components.product',),
        ),
    ]
