# Generated by Django 5.2 on 2025-04-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_ram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='RAM_type',
            new_name='ram_type',
        ),
    ]
