# Generated by Django 5.2 on 2025-04-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_rename_ram_type_ram_ram_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIO',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('size', models.IntegerField(help_text='mm')),
                ('argb', models.BooleanField(default=False)),
                ('max_tdp', models.IntegerField(help_text='Watt')),
            ],
            bases=('components.product',),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('form_factor', models.CharField(default='ATX', max_length=25)),
                ('fans', models.IntegerField(help_text='mm')),
                ('max_cooler_height', models.IntegerField(help_text='mm')),
                ('max_aio_size', models.IntegerField(help_text='mm')),
                ('tempered_glass', models.BooleanField(default=False)),
            ],
            bases=('components.product',),
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('heat_tube_number', models.IntegerField()),
                ('height', models.IntegerField(help_text='mm')),
                ('argb', models.BooleanField(default=False)),
                ('max_tdp', models.IntegerField(help_text='Watt')),
            ],
            bases=('components.product',),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('series', models.CharField(max_length=50)),
                ('wattage', models.IntegerField(help_text='Watt')),
                ('certificate', models.CharField(max_length=25)),
                ('modular', models.BooleanField(default=False)),
            ],
            bases=('components.product',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.product')),
                ('brand', models.CharField(max_length=25)),
                ('capacity', models.CharField(max_length=25)),
                ('storage_type', models.CharField(max_length=25)),
                ('speed', models.IntegerField(help_text='MB/s')),
            ],
            bases=('components.product',),
        ),
    ]
